export const PREFLIGHT_CODES = Object.freeze({
  ACTIVE_MARKDOWN_MISSING: 'ACTIVE_MARKDOWN_MISSING',
  TITLE_EMPTY: 'TITLE_EMPTY',
  SANITIZED_BODY_EMPTY: 'SANITIZED_BODY_EMPTY',
  THEME_INVALID: 'THEME_INVALID',
  LOCAL_ASSET_UNRESOLVED: 'LOCAL_ASSET_UNRESOLVED',
  REMOTE_ASSET_UNRESOLVED: 'REMOTE_ASSET_UNRESOLVED',
  ASSET_RESOLUTION_PENDING: 'ASSET_RESOLUTION_PENDING',
  DIGEST_EMPTY: 'DIGEST_EMPTY',
  CONTENT_SOURCE_NOT_HTTPS: 'CONTENT_SOURCE_NOT_HTTPS',
  NARROW_CONTENT_RISK: 'NARROW_CONTENT_RISK',
  ACCOUNT_MISSING: 'ACCOUNT_MISSING',
  COVER_MISSING: 'COVER_MISSING',
  DRAFT_ACCOUNT_MISMATCH: 'DRAFT_ACCOUNT_MISMATCH',
  TITLE_TOO_LONG: 'TITLE_TOO_LONG',
  AUTHOR_TOO_LONG: 'AUTHOR_TOO_LONG',
  DIGEST_TOO_LONG: 'DIGEST_TOO_LONG',
} as const);

export type PreflightCode = typeof PREFLIGHT_CODES[keyof typeof PREFLIGHT_CODES];
