import { readFile } from 'node:fs/promises';
import { describe, expect, it } from 'vitest';

describe('workbench narrow-layout contract', () => {
  it('keeps toolbar, article, tables, images, long errors, and cover previews bounded', async () => {
    const css = await readFile('styles.css', 'utf8');

    expect(css).toMatch(/wechat-workbench__brand-header\s*\{[^}]*min-height:\s*56px/su);
    expect(css).toMatch(/wechat-workbench__tabs\s*\{[^}]*grid-template-columns:\s*repeat\(2,/su);
    expect(css).toMatch(/--wechat-accent:\s*var\(--interactive-accent\)/su);
    expect(css).not.toMatch(/--wechat-accent:\s*var\(--color-green/su);
    expect(css).toMatch(/wechat-workbench__tabs button\s*\{[^}]*font-size:\s*var\(--font-ui-medium\)/su);
    expect(css).toMatch(/wechat-workbench__settings-section h2\s*\{[^}]*font-size:\s*var\(--font-ui-large\)/su);
    expect(css).toMatch(/wechat-workbench__setting-field\s*\{[^}]*font-size:\s*var\(--font-ui-medium\)/su);
    expect(css).toMatch(/wechat-workbench__action-bar\s*\{[^}]*display:\s*flex/su);
    expect(css).toMatch(/wechat-workbench__style-trigger\s*\{[^}]*margin-left:\s*auto/su);
    expect(css).toMatch(/wechat-workbench__style-trigger\s*\{[^}]*min-width:\s*4rem/su);
    expect(css).toMatch(/wechat-workbench__preview-canvas\s*\{[^}]*background:\s*var\(--background-secondary\)/su);
    expect(css).toMatch(/wechat-workbench__preview-sheet\s*\{[^}]*max-width:\s*52rem/su);
    expect(css).toMatch(/wechat-workbench__preview-sheet\s+img[^}]*max-width:\s*100%/su);
    expect(css).toMatch(/wechat-workbench__cover-preview[^}]*aspect-ratio:\s*2\.35\s*\/\s*1/su);
    expect(css).toMatch(/overflow-wrap:\s*anywhere/gu);
    expect(css).toMatch(/wechat-workbench__preview-stage\s*\{[^}]*display:\s*block/su);
    expect(css).toMatch(/wechat-workbench__body\s*\{[^}]*overflow:\s*hidden/su);
    expect(css).toMatch(/wechat-workbench__preview-canvas\s*\{[^}]*height:\s*100%/su);
    expect(css).toMatch(/wechat-workbench__style-host\s*\{[^}]*position:\s*absolute/su);
    expect(css).toMatch(/wechat-workbench__style-host\s*\{[^}]*width:\s*clamp\(312px,\s*42%,\s*376px\)/su);
    expect(css).toMatch(/wechat-workbench__style-host\[hidden\]\s*\{[^}]*display:\s*none/su);
    expect(css).toMatch(/wechat-workbench\s*\{[^}]*--wechat-style-option-bg:\s*var\(--background-primary\)[^}]*--wechat-style-option-selected-bg:\s*var\(--background-secondary\)[^}]*--wechat-style-option-hover-bg:\s*var\(--background-modifier-hover/su);
    expect(css).toMatch(/wechat-workbench__style-option\s*\{[^}]*background-color:\s*var\(--wechat-style-option-bg\)\s*!important/su);
    expect(css).toMatch(/wechat-workbench__style-option\[aria-pressed="true"\]\s*\{[^}]*background-color:\s*var\(--wechat-style-option-selected-bg\)\s*!important/su);
    expect(css).toMatch(/wechat-workbench__style-option:not\(\[aria-pressed="true"\]\):hover\s*\{[^}]*background-color:\s*var\(--wechat-style-option-hover-bg\)\s*!important/su);
    expect(css).not.toMatch(/wechat-workbench__style-option:hover\s*\{/su);
    expect(css).toMatch(/wechat-workbench__style-switch\s*\{[^}]*min-height:\s*48px[^}]*border:\s*0[^}]*background-color:\s*var\(--wechat-style-option-bg\)\s*!important/su);
    expect(css).toMatch(/wechat-workbench__style-switch-indicator\s*\{[^}]*width:\s*46px[^}]*height:\s*27px[^}]*background:\s*var\(--background-modifier-border\)/su);
    expect(css).toMatch(/wechat-workbench__style-switch\[aria-checked="true"\]\s+\.wechat-workbench__style-switch-indicator\s*\{[^}]*background:\s*var\(--text-normal\)/su);
    expect(css).toMatch(/wechat-workbench__style-body\s*\{[^}]*overflow-y:\s*auto/su);
    expect(css).toMatch(/wechat-workbench__style-header\s*\{[^}]*flex:\s*0 0 auto/su);
    expect(css).toMatch(/wechat-workbench__style-header\s*\{[^}]*position:\s*relative/su);
    expect(css).toMatch(/wechat-workbench__style-header\s*\{[^}]*z-index:\s*2/su);
    expect(css).toMatch(/wechat-workbench__style-header\s*\{[^}]*background:\s*var\(--background-primary\)/su);
    expect(css).toMatch(/wechat-workbench__style-body\s*\{[^}]*scroll-snap-type:\s*y proximity/su);
    expect(css).toMatch(/wechat-workbench__style-section\s*\{[^}]*scroll-snap-align:\s*start/su);
    expect(css).toMatch(/wechat-workbench__style-sizes\s*\{[^}]*grid-template-columns:\s*repeat\(5,/su);
    expect(css).toMatch(/wechat-workbench__style-captions\s*\{[^}]*grid-template-columns:\s*repeat\(2,/su);
    expect(css).toMatch(/wechat-workbench__style-select-row\s*\{[^}]*grid-template-columns:/su);
    expect(css).toMatch(/wechat-workbench__style-select-trigger\s*\{[^}]*line-height:\s*normal/su);
    expect(css).toMatch(/wechat-workbench__style-select-menu\s*\{[^}]*position:\s*absolute/su);
    expect(css).toMatch(/wechat-workbench__style-select\.is-open\s+\.wechat-workbench__style-select-menu\s*\{[^}]*display:\s*block/su);
    expect(css).toMatch(/wechat-workbench__style-toggle-row\s*\{[^}]*justify-content:\s*space-between/su);
    expect(css).not.toMatch(/wechat-workbench__style-select-label\s+select/u);
    expect(css).not.toMatch(/(?:^|\n)\s*(?:button|input|select|h1|p)\s*\{/mu);
    expect(css).not.toMatch(/wechat-workbench__account-status/u);
  });
});
