import { readFile } from 'node:fs/promises';
import { describe, expect, it } from 'vitest';

describe('workbench narrow-layout contract', () => {
  it('keeps toolbar, article, tables, images, long errors, and cover previews bounded', async () => {
    const css = await readFile('styles.css', 'utf8');

    expect(css).toMatch(/wechat-workbench__brand-header\s*\{[^}]*min-height:\s*30px/su);
    expect(css).toMatch(/wechat-workbench__tabs\s*\{[^}]*grid-template-columns:\s*repeat\(2,[^}]*min-height:\s*44px/su);
    expect(css).toMatch(/--wechat-accent:\s*#07c160/isu);
    expect(css).not.toMatch(/interactive-accent/u);
    expect(css).toMatch(/wechat-workbench__tabs button\s*\{[^}]*position:\s*relative[^}]*background:\s*transparent[^}]*font-size:\s*var\(--font-ui-medium\)/su);
    expect(css).toMatch(/wechat-workbench__tabs button\.is-active::after\s*\{[^}]*height:\s*3px[^}]*background:\s*var\(--wechat-accent\)/su);
    expect(css).toMatch(/wechat-workbench__settings-section h2\s*\{[^}]*color:\s*var\(--text-normal\)[^}]*font-size:\s*var\(--font-ui-large\)/su);
    expect(css).toMatch(/wechat-workbench__setting-field\s*\{[^}]*font-size:\s*var\(--font-ui-medium\)/su);
    expect(css).toMatch(/wechat-workbench__setting-field\s*\{[^}]*min-width:\s*0[^}]*max-width:\s*100%/su);
    expect(css).toMatch(/wechat-workbench\s+\.wechat-workbench__setting-field input,\s*\.wechat-workbench\s+\.wechat-workbench__setting-field textarea\s*\{[^}]*box-sizing:\s*border-box[^}]*min-width:\s*0[^}]*max-width:\s*100%/su);
    expect(css).toMatch(/wechat-workbench__ai-candidates\s*\{[^}]*min-width:\s*0[^}]*max-width:\s*100%/su);
    expect(css).toMatch(/wechat-workbench__ai-candidates\s*\{[^}]*background:\s*transparent/su);
    expect(css).toMatch(/wechat-workbench__ai-candidates\s*\{[^}]*border:\s*1px solid var\(--background-modifier-border\)/su);
    expect(css).toMatch(/wechat-workbench\s+\.wechat-workbench__setting-field input:focus-visible,\s*\.wechat-workbench\s+\.wechat-workbench__setting-field textarea:focus-visible\s*\{[^}]*border-color:\s*var\(--background-modifier-border\)[^}]*box-shadow:\s*0 0 0 2px var\(--background-modifier-border-focus\)/su);
    expect(css).toMatch(/wechat-workbench__cover-thumb\[data-preview-url\]:hover,\s*\.wechat-workbench__cover-thumb\[data-preview-url\]:focus-visible\s*\{[^}]*border-color:\s*var\(--background-modifier-border\)/su);
    expect(css).toMatch(/wechat-workbench__ai-candidate\s*\{[^}]*min-width:\s*0[^}]*max-width:\s*100%[^}]*overflow-wrap:\s*anywhere/su);
    expect(css).toMatch(/wechat-workbench__action-bar\s*\{[^}]*display:\s*flex[^}]*min-height:\s*52px/su);
    expect(css).toMatch(/wechat-workbench__style-trigger\s*\{[^}]*margin-left:\s*auto/su);
    expect(css).toMatch(/wechat-workbench__style-trigger\s*\{[^}]*min-width:\s*4rem/su);
    expect(css).toMatch(/wechat-workbench__preview-canvas\s*\{[^}]*background:\s*var\(--background-secondary\)/su);
    expect(css).toMatch(/wechat-workbench__preview-sheet\s*\{[^}]*max-width:\s*52rem/su);
    expect(css).toMatch(/wechat-workbench__preview-sheet\s+img[^}]*max-width:\s*100%/su);
    expect(css).toMatch(/wechat-workbench__cover-preview[^}]*aspect-ratio:\s*2\.35\s*\/\s*1/su);
    expect(css).toMatch(/wechat-workbench__cover-preview-modal\s*\{[^}]*width:\s*100%\s*!important[^}]*max-width:\s*100%\s*!important[^}]*max-height:\s*calc\(100vh - 2rem\)[^}]*overflow:\s*hidden/su);
    expect(css).toMatch(/wechat-workbench__cover-preview-modal-shell\s*\{[^}]*width:\s*min\(90vw,\s*57\.333rem\)\s*!important[^}]*max-width:\s*calc\(100vw - 2rem\)\s*!important/su);
    expect(css).toMatch(/wechat-workbench__cover-preview-modal\s+\.wechat-workbench__cover-preview-image\s*\{[^}]*width:\s*auto\s*!important[^}]*max-width:\s*100%\s*!important[^}]*max-height:\s*calc\(100vh - 8rem\)\s*!important/su);
    expect(css).toMatch(/overflow-wrap:\s*anywhere/gu);
    expect(css).toMatch(/wechat-workbench__preview-stage\s*\{[^}]*display:\s*block/su);
    expect(css).toMatch(/wechat-workbench__body\s*\{[^}]*overflow:\s*hidden/su);
    expect(css).toMatch(/wechat-workbench__preview-canvas\s*\{[^}]*height:\s*100%/su);
    expect(css).toMatch(/wechat-workbench__style-host\s*\{[^}]*position:\s*absolute/su);
    expect(css).toMatch(/wechat-workbench__style-host\s*\{[^}]*width:\s*clamp\(312px,\s*42%,\s*376px\)/su);
    expect(css).toMatch(/wechat-workbench__style-host\[hidden\]\s*\{[^}]*display:\s*none/su);
    expect(css).toMatch(/wechat-workbench\s*\{[^}]*--wechat-style-option-bg:\s*var\(--background-primary\)[^}]*--wechat-style-option-selected-bg:\s*var\(--background-secondary\)[^}]*--wechat-style-option-hover-bg:\s*var\(--background-modifier-hover/su);
    expect(css).toMatch(/wechat-workbench__style-option\s*\{[^}]*background-color:\s*var\(--wechat-style-option-bg\)\s*!important/su);
    expect(css).toMatch(/wechat-workbench__style-option\[aria-pressed="true"\]\s*\{[^}]*background-color:\s*var\(--wechat-style-option-selected-bg\)\s*!important/su);
    expect(css).toMatch(/wechat-workbench__style-option:not\(\[aria-pressed="true"\]\):hover\s*\{[^}]*background-color:\s*var\(--wechat-style-option-hover-bg\)\s*!important/su);
    expect(css).not.toMatch(/wechat-workbench__style-option:hover\s*\{/su);
    expect(css).toMatch(/wechat-workbench__style-switch\s*\{[^}]*min-height:\s*48px[^}]*border:\s*0[^}]*background-color:\s*var\(--wechat-style-option-bg\)\s*!important/su);
    expect(css).toMatch(/wechat-workbench__style-switch-indicator\s*\{[^}]*width:\s*46px[^}]*height:\s*27px[^}]*background:\s*var\(--background-modifier-border\)/su);
    expect(css).toMatch(/wechat-workbench__style-switch\[aria-checked="true"\]\s+\.wechat-workbench__style-switch-indicator\s*\{[^}]*background:\s*var\(--text-normal\)/su);
    expect(css).toMatch(/wechat-workbench__style-body\s*\{[^}]*overflow-y:\s*auto/su);
    expect(css).toMatch(/wechat-workbench__style-header\s*\{[^}]*flex:\s*0 0 auto/su);
    expect(css).toMatch(/wechat-workbench__style-header\s*\{[^}]*position:\s*relative/su);
    expect(css).toMatch(/wechat-workbench__style-header\s*\{[^}]*z-index:\s*2/su);
    expect(css).toMatch(/wechat-workbench__style-header\s*\{[^}]*background:\s*var\(--background-primary\)/su);
    expect(css).toMatch(/wechat-workbench__style-body\s*\{[^}]*scroll-snap-type:\s*y proximity/su);
    expect(css).toMatch(/wechat-workbench__style-section\s*\{[^}]*scroll-snap-align:\s*start/su);
    expect(css).toMatch(/wechat-workbench__style-sizes\s*\{[^}]*grid-template-columns:\s*repeat\(5,/su);
    expect(css).toMatch(/wechat-workbench__style-captions\s*\{[^}]*grid-template-columns:\s*repeat\(2,/su);
    expect(css).toMatch(/wechat-workbench__style-select-row\s*\{[^}]*grid-template-columns:/su);
    expect(css).toMatch(/wechat-workbench__style-select-trigger\s*\{[^}]*line-height:\s*normal/su);
    expect(css).toMatch(/wechat-workbench__style-select-menu\s*\{[^}]*position:\s*absolute/su);
    expect(css).toMatch(/wechat-workbench__style-select\.is-open\s+\.wechat-workbench__style-select-menu\s*\{[^}]*display:\s*block/su);
    expect(css).toMatch(/wechat-workbench__style-toggle-row\s*\{[^}]*justify-content:\s*space-between/su);
    expect(css).toMatch(/wechat-workbench-settings__account-card\s*\{[^}]*border:\s*1px solid var\(--background-modifier-border\)/su);
    expect(css).toMatch(/wechat-workbench-settings__actions\s*\{[^}]*display:\s*flex[^}]*flex-wrap:\s*wrap[^}]*gap:\s*8px/su);
    expect(css).toMatch(/wechat-workbench-settings__account-status\s*\{[^}]*border-top:\s*1px solid var\(--background-modifier-border\)/su);
    expect(css).toMatch(/wechat-workbench-settings__section-title\s*\{[^}]*margin-left:\s*0[^}]*padding-left:\s*0/su);
    expect(css).toMatch(/wechat-workbench-settings__account-guidance\s*\{[^}]*display:\s*grid[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)/su);
    expect(css).toMatch(/wechat-workbench-settings__account-guidance-copy\s*\{[^}]*min-width:\s*0/su);
    expect(css).toMatch(/wechat-workbench-settings__ai-model-field\.has-fetched-models\s+\.wechat-workbench-settings__ai-model-control\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+2\.5rem/su);
    expect(css).toMatch(/wechat-workbench-settings__ai-model-picker\s*\{[^}]*height:\s*auto/su);
    expect(css).toMatch(/wechat-workbench-settings__ai-actions\s*>\s*button\.mod-cta\s*\{[^}]*background:\s*var\(--wechat-workbench-settings-accent\)[^}]*border-color:\s*var\(--wechat-workbench-settings-accent\)/su);
    expect(css).not.toMatch(/@media\s*\(max-width:\s*900px\)[\s\S]*wechat-workbench-settings__ai-model-field\.has-fetched-models[^{]*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)/u);
    expect(css).toMatch(/wechat-workbench-settings__ai-model-menu\s*\{[^}]*overflow-y:\s*auto[^}]*position:\s*fixed/su);
    expect(css).toMatch(/wechat-workbench-settings__actions\s*>\s*\[data-testid="account-open-console"\]\s*\{[^}]*margin-left:\s*auto[^}]*border:\s*1px solid var\(--background-modifier-border\)[^}]*color:\s*var\(--text-normal\)[^}]*background:\s*var\(--background-modifier-hover\)[^}]*font-weight:\s*var\(--font-semibold\)/su);
    expect(css).toMatch(/wechat-workbench__cover-generation-config\s+\.wechat-workbench__cover-prompt-label select\s*\{[^}]*appearance:\s*none[^}]*background-image:\s*url\(/su);
    expect(css).toMatch(/wechat-workbench__cover-generation-config\s+\.wechat-workbench__cover-content-options\s*\{[^}]*justify-self:\s*start/su);
    expect(css).toMatch(/wechat-workbench__cover-content-options\s*>\s*span\s*\{[^}]*font-weight:\s*700/su);
    expect(css).toMatch(/wechat-workbench\s+\.wechat-workbench__setting-field input,\s*\.wechat-workbench\s+\.wechat-workbench__setting-field textarea\s*\{[^}]*min-height:\s*2\.5rem[^}]*border:\s*1px solid var\(--background-modifier-border\)[^}]*border-radius:\s*var\(--radius-s\)/su);
    expect(css).not.toMatch(/wechat-workbench-settings__ai-card\s+\.setting-item\s*\{/u);
    expect(css).not.toMatch(/wechat-workbench-settings__ai-card\s+\.setting-item-name\s*\{/u);
    expect(css).not.toMatch(/wechat-workbench-settings__ai-card\s+\.setting-item-control\s*\{/u);
    expect(css).not.toMatch(/wechat-workbench__style-select-label\s+select/u);
    expect(css).not.toMatch(/(?:^|\n)\s*(?:button|input|select|h1|p)\s*\{/mu);
    expect(css).not.toMatch(/wechat-workbench__account-status/u);
  });
});
